### ISSUE TITLE
Support for daily snippets

### ISSUE THREAD

**Issue by parkan** [Khan/snippets#25]
Ended up jumping into deploying this without realizing that there's no daily (rather than weekly) reminder setting. Any thoughts on this? Seems like it wouldn't be too hard to add a daily/weekly reminder setting and possibly group them by day under each user in /weekly.

**Comment by csilvers** [comment]
I thought I  understood what you were asking up into the last sentence.  What do you mean by "daily reminder?"  Do you mean, an email that goes out daily reminding people to update their snippets?  Or do you mean that we support daily snippets, not just weekly snippets?  Or something else?  What is the problem you are trying to solve?

**Comment by parkan** [comment]
@csilvers sorry, I guess I ended up kind of muddying the matter -- the goal is to have daily snippets, but perhaps simply having the option of daily reminders will be a least-effort way to approximate that.

**Comment by csilvers** [comment]
Philosophically, I feel daily snippets is too frequent (though of course people are welcome to update their weekly snippets daily or hourly or minutely if they'd like).  So a pull request that changes snippets to show daily snippets (`/daily` or what have you) faces a tough sell.

But if you wanted to change the cron job so it ran every day instead of once a week, I think it's just a small change to cron.yaml. You might want to adjust the text of the reminder email as well.

**Comment by parkan** [comment]
Ok, after thinking about this some more adapting the existing UX to the pattern that we want will probably be too much work. Closing!
